[package]
name = "itsmine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
clap = { version = "4.5.51", features = ["derive"] }
log = "0.4.20"

[profile.dev]
opt-level = 0
lto = false

[profile.release]
opt-level = 0
lto = false
